version: "3"

tasks:
  frontend:
    dir: "{{.USER_WORKING_DIR}}/frontend"
    cmds:
      - npm install --force
      - npm run build

  test:
    cmds:
      - go test ./...

  run_pprof:
    deps:
      - frontend
    cmds:
      - go run -tags pprof,dev .
    summary: |
      Runs the application with CPU profiling enabled.
