// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutodetectGameDir() {
  return window['go']['config']['API']['AutodetectGameDir']();
}

export function GetConfig() {
  return window['go']['config']['API']['GetConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['config']['API']['SaveConfig'](arg1);
}

export function ValidateGameDir(arg1) {
  return window['go']['config']['API']['ValidateGameDir'](arg1);
}

export function ValidateInfluxBucket(arg1) {
  return window['go']['config']['API']['ValidateInfluxBucket'](arg1);
}

export function ValidateInfluxHost(arg1) {
  return window['go']['config']['API']['ValidateInfluxHost'](arg1);
}

export function ValidateInfluxOrg(arg1) {
  return window['go']['config']['API']['ValidateInfluxOrg'](arg1);
}

export function ValidateInfluxPort(arg1) {
  return window['go']['config']['API']['ValidateInfluxPort'](arg1);
}

export function ValidateInfluxToken(arg1) {
  return window['go']['config']['API']['ValidateInfluxToken'](arg1);
}
