// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutodetectGameDir() {
  return window['go']['config']['Config']['AutodetectGameDir']();
}

export function ValidateGameDir(arg1) {
  return window['go']['config']['Config']['ValidateGameDir'](arg1);
}

export function ValidateInfluxBucket(arg1) {
  return window['go']['config']['Config']['ValidateInfluxBucket'](arg1);
}

export function ValidateInfluxHost(arg1) {
  return window['go']['config']['Config']['ValidateInfluxHost'](arg1);
}

export function ValidateInfluxOrg(arg1) {
  return window['go']['config']['Config']['ValidateInfluxOrg'](arg1);
}

export function ValidateInfluxPort(arg1) {
  return window['go']['config']['Config']['ValidateInfluxPort'](arg1);
}

export function ValidateInfluxToken(arg1) {
  return window['go']['config']['Config']['ValidateInfluxToken'](arg1);
}
