// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */

//////////
// source: app.go

/**
 * App struct
 */
export interface App {
}
/**
 * AppInfo contains information about the app itself.
 */
export interface AppInfo {
  ProjectName: string;
  Version: string;
  Commit: string;
  GithubURL: string;
}
/**
 * ReleaseInfo contains information about a release (of this binary).
 */
export interface ReleaseInfo {
  IsNewer: boolean;
  Version: string;
  Commitish: string;
  PublishedAt: string /* RFC3339 */;
  Changelog: string;
}

//////////
// source: events.go

export interface EventNames {
  NewRound: string;
  RoundWatcherStarted: string;
  RoundWatcherError: string;
  RoundWatcherStopped: string;
  LatestReleaseInfo: string;
  LatestReleaseInfoErr: string;
  UpdateProgress: string;
  UpdateErr: string;
}
