// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */

//////////
// source: conn.go

export interface InfluxClient {
  URL: string;
}
export interface ConnectOpts {
  URL: string;
  Token: string;
  Org: string;
  Bucket: string;
}
export interface ConnectionDetails {
  Name: string;
  Version: string;
  Commit: string;
}
