// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';
import {db} from '../models';

export function AutodetectGameDir():Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetVersion():Promise<main.BuildInfo>;

export function GetWindowTitle():Promise<string>;

export function SaveAndValidateConfig(arg1:config.Config):Promise<db.ConnectionDetails>;

export function ValidateGameDir(arg1:string):Promise<void>;

export function ValidateInfluxBucket(arg1:string):Promise<void>;

export function ValidateInfluxHost(arg1:string):Promise<void>;

export function ValidateInfluxOrg(arg1:string):Promise<void>;

export function ValidateInfluxPort(arg1:string):Promise<void>;

export function ValidateInfluxToken(arg1:string):Promise<void>;
