// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutodetectGameDir() {
  return window['go']['main']['App']['AutodetectGameDir']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWindowTitle() {
  return window['go']['main']['App']['GetWindowTitle']();
}

export function OpenGameDirDialog() {
  return window['go']['main']['App']['OpenGameDirDialog']();
}

export function SaveAndValidateConfig(arg1) {
  return window['go']['main']['App']['SaveAndValidateConfig'](arg1);
}

export function SubscribeMatches() {
  return window['go']['main']['App']['SubscribeMatches']();
}

export function ValidateGameDir(arg1) {
  return window['go']['main']['App']['ValidateGameDir'](arg1);
}

export function ValidateInfluxBucket(arg1) {
  return window['go']['main']['App']['ValidateInfluxBucket'](arg1);
}

export function ValidateInfluxHost(arg1) {
  return window['go']['main']['App']['ValidateInfluxHost'](arg1);
}

export function ValidateInfluxOrg(arg1) {
  return window['go']['main']['App']['ValidateInfluxOrg'](arg1);
}

export function ValidateInfluxPort(arg1) {
  return window['go']['main']['App']['ValidateInfluxPort'](arg1);
}

export function ValidateInfluxToken(arg1) {
  return window['go']['main']['App']['ValidateInfluxToken'](arg1);
}
