// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AutodetectGameDir():Promise<string>;

export function Connect():Promise<any>;

export function Disconnect():Promise<void>;

export function GetAppInfo():Promise<any>;

export function GetConfig():Promise<any>;

export function GetEventNames():Promise<main.EventNames>;

export function GetWindowTitle():Promise<string>;

export function IsConfigComplete():Promise<boolean>;

export function OpenGameDirDialog():Promise<string>;

export function RequestLatestReleaseInfo():Promise<void>;

export function SaveAndValidateConfig(arg1:any):Promise<any>;

export function StartReleaseWatcher():Promise<void>;

export function StartRoundWatcher():Promise<void>;

export function StartUpdate():Promise<void>;

export function StopRoundWatcher():Promise<void>;

export function ValidateGameDir(arg1:string):Promise<void>;

export function ValidateInfluxBucket(arg1:string):Promise<void>;

export function ValidateInfluxHost(arg1:string):Promise<void>;

export function ValidateInfluxOrg(arg1:string):Promise<void>;

export function ValidateInfluxPort(arg1:string):Promise<void>;

export function ValidateInfluxToken(arg1:string):Promise<void>;
