// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutodetectGameDir() {
  return window['go']['main']['App']['AutodetectGameDir']();
}

export function Connect() {
  return window['go']['main']['App']['Connect']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetEventNames() {
  return window['go']['main']['App']['GetEventNames']();
}

export function GetWindowTitle() {
  return window['go']['main']['App']['GetWindowTitle']();
}

export function IsConfigComplete() {
  return window['go']['main']['App']['IsConfigComplete']();
}

export function OpenGameDirDialog() {
  return window['go']['main']['App']['OpenGameDirDialog']();
}

export function RequestLatestReleaseInfo() {
  return window['go']['main']['App']['RequestLatestReleaseInfo']();
}

export function SaveAndValidateConfig(arg1) {
  return window['go']['main']['App']['SaveAndValidateConfig'](arg1);
}

export function StartReleaseWatcher() {
  return window['go']['main']['App']['StartReleaseWatcher']();
}

export function StartRoundWatcher() {
  return window['go']['main']['App']['StartRoundWatcher']();
}

export function StartUpdate() {
  return window['go']['main']['App']['StartUpdate']();
}

export function ValidateGameDir(arg1) {
  return window['go']['main']['App']['ValidateGameDir'](arg1);
}

export function ValidateInfluxBucket(arg1) {
  return window['go']['main']['App']['ValidateInfluxBucket'](arg1);
}

export function ValidateInfluxHost(arg1) {
  return window['go']['main']['App']['ValidateInfluxHost'](arg1);
}

export function ValidateInfluxOrg(arg1) {
  return window['go']['main']['App']['ValidateInfluxOrg'](arg1);
}

export function ValidateInfluxPort(arg1) {
  return window['go']['main']['App']['ValidateInfluxPort'](arg1);
}

export function ValidateInfluxToken(arg1) {
  return window['go']['main']['App']['ValidateInfluxToken'](arg1);
}
