name: Review

on:
  pull_request: {}
  pull_request_review_comment:
    types: [created, edited]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    name: golangci-lint
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3.4.0
      - name: Run golangci-lint with reviewdog
        uses: reviewdog/action-golangci-lint@v2.2.2
