name: Test Release (Snapshot)

on:
  pull_request: {}
  pull_request_review_comment:
    types: [created, edited]
  workflow_dispatch:

jobs:
  build_snapshot:
    uses: ./.github/workflows/release_generic.yml
    with:
      snapshot: true
